version: "3"

services:
  database:
    image: postgres:13.3
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '5432:5434'
    env_file: .env

  redis:
    image: 'redis:7-alpine'

volumes:
  database:
    driver: local
