version: "3"

services:
  database:
    image: postgres:13.3
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5434
    env_file: .env

  redis:
    image: 'redis:7-alpine'

volumes:
  postgres:
