production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['PUMA_MAX_THREADS'] || 16 %>

development:
  adapter: postgresql
  database: <%= ENV.fetch('DATABASE_NAME', 'monet') %>
  host: <%= ENV.fetch('DATABASE_HOST', '172.20.0.2') %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  adapter: postgresql
  database: monet_test
  host: <%= ENV.fetch('DATABASE_HOST', '172.20.0.2') %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
